### ISSUE TITLE
Repostructure Branch name as major odoo version

### ISSUE THREAD

**Issue by bosd** [monero-integrations/moneroodoo#7]
@serhack 
Best practice is to use major odoo version as branch name in the repo.
Please create branch
`14.0`
`15.0`

I'll do some code restucturing from the master branch and create a new pr to the 14.0 branch when ready.

**Comment by bosd** [comment]
Went ahead with the development and renaming of modules. They are now in https://github.com/bosd/moneroodoo.
It cannot automatically be merged into the master branch of this repo.

@serhack When you're ready, please add an new empty 14.0 branch in this repo.
Then I will create a PR from my 14.0 branch to this repo.

**Comment by bosd** [comment]
ping @cryptochangements34

**Comment by serhack** [comment]
@bosd Thanks for your interest! Sorry, I missed the notification. I have created two branches: 14.0 and 15.0. Feel free to open a new PR :)

**Comment by bosd** [comment]
draft pr in: https://github.com/monero-integrations/moneroodoo/pull/9
